format_version: 10
pipelines:
  build:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-64bfbc3:
        git: https://github.com/yanyuxin003/project.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - testbuild:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          buildTest:
            timeout: 0
            tasks:
            - exec:
                command: build
                run_if: passed
